name: demo
on:
  workflow_run:
    workflows:
      - build-test
    types: [ completed ]

jobs:
  comment-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - uses: quipper/comment-failure-action@v0.1.0
